//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMMON {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RSSQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RSSQL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COMMON.RSSQL", typeof(RSSQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T.STRSTATUS 
        ///FROM ( 
        ///SELECT A.STRPROGRAMNAME,A.STRSTATUS,A.DTERUNDATE  
        ///FROM {0}.BOTT_LOG_HEADER A  
        ///WHERE TO_CHAR(A.DTERUNDATE,&apos;YYYYMMDD&apos;) = &apos;{1}&apos; 
        ///AND A.STRPROGRAMNAME =&apos;{2}&apos; 
        ///ORDER BY  A.DTERUNDATE DESC 
        ///) T 
        ///WHERE ROWNUM=1.
        /// </summary>
        public static string SQL_GET_LOGSTATUS {
            get {
                return ResourceManager.GetString("SQL_GET_LOGSTATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ROWNUM, S.*
        ///  FROM(SELECT   RECNO, PROGRAMNAME, PROGRAMDESC, CONTINUEERR, WAITPROGRAM,
        ///                 TIMELIMIT, PATHEXE, PROGRAMTYPE, PROGRAMGROUP, PATHGETFILE,
        ///                 FILENAME
        ///            FROM {0}.BOTM_NTF_SET_SCHEDULE S
        ///           WHERE PROGRAMTYPE = &apos;{1}&apos; AND PROGRAMGROUP = &apos;{2}&apos;
        ///        ORDER BY RECNO) S.
        /// </summary>
        public static string SQL_GET_SCHEDULED {
            get {
                return ResourceManager.GetString("SQL_GET_SCHEDULED", resourceCulture);
            }
        }
    }
}
